import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DockDemo } from "@/components/dock-menu";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

          <main className="dark:bg-black bg-white dark:bg-opacity-20 bg-opacity-20">
            {children}
            <div className="container pt-10 sticky">
              <DockDemo />
            </div>
            
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
